### ISSUE TITLE
Gestione inserimento pietre (stone) nella board

### ISSUE THREAD

**Issue by martat97** [mikedepetris/Gomoku-SDM#10]
Come possiamo inserire le pietre nere/bianche nella board?
Al momento alla board è associata una matrice di interi 19x19.
Può essere una matrice di interi che assume di default 0, poi può essere 1 se la pietra è nera, 2 se la pietra è bianca.
Poi applichiamo il processo di refactoring, ma questo è il metodo più semplice, provo a mettere questo intanto nel codice

**Comment by mikedepetris** [comment]
mmmmmmm matrice di interi, la board forse dovrebbe essere un oggetto contenente una collezione di posizioni, a ciascuna corrisponde un Coordinates ed uno stato che indica Empty, White, Black

**Comment by martat97** [comment]
lo chiedevo perchè ho visto che è associata una matrice int e non capivo perchè, magari è stato messo solo di default. comunque a questo punto un po' mi sfugge la relazione che si vuole fare tra board, stone, coordinates.
noi possiamo inserire un oggetto stone in una matrice associata a board. a questo punto non verrebbe associata alcuna coordinata a stone, perchè mi basta accedere alle posizioni della matrice.
è un po' da chiarire (almeno per me), la relazione fra queste classi

**Comment by biagiolicari** [comment]
> mmmmmmm matrice di interi, la board forse dovrebbe essere un oggetto contenente una collezione di posizioni, a ciascuna corrisponde un Coordinates ed uno stato che indica Empty, White, Black

- Facendo così, dovremmo inserire all'interno della classe Colour lo stato empty e creare la board come una lista di Stone con colore empty, controllando se una mossa è valida effettuando un check sullo stato della pietra e se e valida settare il colore bianco/nero

-Dovrebbero essere inserite delle funzioni che permettono di recuperare dalla lista di coordinate, le coordinate prossime all'attuale in tutte le posizioni adiacenti per la verifica delle 5 stones consecutive

**Comment by biagiolicari** [comment]
> lo chiedevo perchè ho visto che è associata una matrice int e non capivo perchè, magari è stato messo solo di default. comunque a questo punto un po' mi sfugge la relazione che si vuole fare tra board, stone, coordinates.
> noi possiamo inserire un oggetto stone in una matrice associata a board. a questo punto non verrebbe associata alcuna coordinata a stone, perchè mi basta accedere alle posizioni della matrice.
> è un po' da chiarire (almeno per me), la relazione fra queste classi

La board è creata come int[][]  come 'base' da cui fare refactor, se adottiamo il metodo di creare la matrice come lista di Stones bisogna valutare se concettualmente è utile mantenere la classe Stone, Coordinate, entrambe o trasformare Coordinate come interfaccia o toglierla del tutto

**Comment by martat97** [comment]
ok, bisognerà discutere per trovare il modo più "pulito", quindi più efficiente, con solo le classi necessarie, per implementare questo. poi si potrà visualizzare la board

**Comment by mikedepetris** [comment]
sta spiegando nella lezione di oggi 24/11/22 la parte dei code smell "primitive obsession" che riguarda questo caso. In sostanza implementerei come array per poi valutare se conviene fare un refactoring creando classi con i nomi opportuni che descrivano oggetti al posto delle primitive array di int.

**Comment by martat97** [comment]
Va bene ottimo, guarderò la registrazione
