### ISSUE TITLE
Possibili violazioni di principi SOLID: 3. L - Liskov Substitution Principle

### ISSUE THREAD

**Issue by martat97** [mikedepetris/Gomoku-SDM#104]
https://www.html.it/pag/32393/l-liskov-substitution-principle/
Se per ogni oggetto O1 di tipo S c'è un oggetto O2 di tipo T, tale che per tutti i programmi P definiti in termini di T, il comportamento di P non vari sostituendo O1 a O2, allora S è un sottotipo di T

**Comment by martat97** [comment]
Riporto in alto questo principio perchè è (forse) l'unico principio che non abbiamo discusso. Riguarderebbe applicare ereditarietà alle classi

**Comment by mikedepetris** [comment]
Non mi pare abbiamo applicato l'ereditarietà per molte classi, identifichiamo quali sono, verifichiamo che il principio non sia violato e chiudiamo
