### ISSUE TITLE
Refactoring classe Game

### ISSUE THREAD

**Issue by biagiolicari** [mikedepetris/Gomoku-SDM#116]
Refactoring della classe Game:

-Refactoring funzione che controlla la vittoria, cercando di semplificarla
-Controllo rispetto principi SOLID ed eventuale refactoring
-Refactoring generale del codice

**Comment by mikedepetris** [comment]
riusciamo a chiudere fare merge? La parte di refactoring della classe ci blocca sull'estensione dei test e le altre considerazioni, sarebbe meglio eventualmente creare issue più specifici  e non tenere branch aperti così a lungo, dimmi se serve un confronto
