### ISSUE TITLE
Refactoring Counting Stones in Game

### ISSUE THREAD

**Issue by martat97** [mikedepetris/Gomoku-SDM#127]
Per migliorare counting stones nella classe game. Per ora non è male ma si può fare di meglio.

**Comment by mikedepetris** [comment]
ok

**Comment by martat97** [comment]
sarei dell'idea di chiudere la issue, al momento secondo me va abbastanza bene

**Comment by mikedepetris** [comment]
chiudiamo per tenere le cose più importanti
