### ISSUE TITLE
Bug: non dà errore se scrivi due username uguali

### ISSUE THREAD

**Issue by martat97** [mikedepetris/Gomoku-SDM#132]
Ho testato il gioco, e scrivendo due nomi identici non dà errore.
Probabilmente perchè con la CLI non vengono inizializzati subito gli username (cosa che secondo me non va bene)

**Comment by biagiolicari** [comment]
Son d’accordo con te sul dettare i nomi in seguito, credo sia sbagliato.
Anche perché guardando il codice il check sul nome viene fatto all’interno del costruttore quando i due player hanno teoreticamente inizializzazione “”, se non sbaglio
