### ISSUE TITLE
GUI: non viene effettuato il controllo che i nomi dei giocatori non siano uguali

### ISSUE THREAD

**Issue by mikedepetris** [mikedepetris/Gomoku-SDM#156]
Viene istanziato Game() con nomi di giocatori vuoti e poi vengono impostati con quelli scritti nelle textbox ma a quel punto non viene eseguito il controllo

**Comment by martat97** [comment]
Questo ho provato a vederlo, ma non ho risolto, non so come mai non lancia l'eccezione più che altro quando vado a inserire i due player uguali, se lo facesse, basterebbe rilevare l'eccezione, non eseguire il gioco, e settare nel title la scritta che avvisa la presenza di due player uguali

**Comment by mikedepetris** [comment]
OK sto guardando io

**Comment by martat97** [comment]
Grazie mike! Purtroppo nel pomeriggio devo vedere di un'altra materia, intanto alcuni problemi della gui li ho risolti, al momento rimangono "solo" due poi dovrebbe essere ok
