### ISSUE TITLE
GUI: errore nella multipla creazione di un game

### ISSUE THREAD

**Issue by martat97** [mikedepetris/Gomoku-SDM#162]
Inizialmente se schiaccio play ed eseguo il gioco, tutto ok. Quando esco dal gioco anche a metà partita cliccando su back to main menu, e torno a schiacciare play, mi aspetto che mi ricrei un gioco da capo e ricominci. Però qualsiasi mossa io tenti di fare mi lancia l'eccezione. Qualcuno di voi ha qualche idea del perchè? Provate

**Comment by mikedepetris** [comment]
Invece di assegnare a tutti la issue, che si assegnerà solo chi la prenderà in carico, provo a mettere la label "help wanted" e taggare gli altri @biagiolicari e @FedericoCalandra

**Comment by mikedepetris** [comment]
non succede più probabilmente a seguito delle ultime modifiche e correzioni, chiudo

**Comment by mikedepetris** [comment]
a me non succede, dovresti farmelo vedere, ma succede a qualcun altro?

**Comment by martat97** [comment]
Faccio uno screenshot così è più chiaro

**Comment by martat97** [comment]
Descrivo precisamente le operazioni effettuate sulla GUI. Allora il settings l'ho lasciato a 19x19 (quindi non ho neanche cliccato sul pulsante Settings)
Clicco su play, simulo una partita in cui vince Player 1 (il nero), clicco su Back to Main Menu.
Ora clicco nuovamente su Play, e quello che mi mostra sopra è una scritta che indica sempre Invalid Move nonostante piazzi a livello grafico le stones. Cosa molto strana, perchè poi computa comunque la vittoria.
E' come se facesse makeMove e lanciasse un'eccezione lo stesso. Che strano
![sdm invalid move](https://user-images.githubusercontent.com/38936469/215834668-c57f851e-a31a-4cdf-b43f-6768c0e978ec.JPG)

**Comment by mikedepetris** [comment]
ok ora ho capito e me la assegno, non avevo notato la scritta in alto visto che il gioco continua a funzionare
