### ISSUE TITLE
creazione classi base

### ISSUE THREAD

**Issue by mikedepetris** [mikedepetris/Gomoku-SDM#2]
CLASSI BASE PER IL GIOCO
Player -> rappresenta il giocatore. è costituto dallo username, dal colore associato, dalla lista mosse (sarebbe una lista di stones, a cosa serve?)
Board -> rappresenta la "scacchiera" 19x19 (per il momento impostiamo la dimensione standard), è associata una matrice di tipologia ancora da definire
Stone -> rappresenta la pedina, con il colore nero/bianco e (per il momento) la posizione nella board con coordinates. questo è da discutere perchè la posizione è raggiungibile nella matrice associata a board. potrebbe essere un modo per tenere traccia della posizione dopo ogni mossa
Coordinates -> serve farlo? per ora sì, se vogliamo associare la posizione a Stone

**Comment by martat97** [comment]
Ho aggiornato il commento per la struttura classi

**Comment by martat97** [comment]
Chiusa la issue, le classi base le abbiamo create
