### ISSUE TITLE
E' giusto mettere getAdjacentCoordinates() nella classe Coordinates?

### ISSUE THREAD

**Issue by martat97** [mikedepetris/Gomoku-SDM#38]
Siamo sicuri di voler mettere getAdjacentCoordinates() nella classe Coordinates? 
Per trovare le coordinate adiacenti ci serve la dimensione della board per soddisfare la condizione che le coordinate siano < 19 (in questo caso)
Forse meglio board.getAdjacentCoordinates(coordinata/cella) così abbiamo già la dimensione della board?
O comunque in qualche altra classe, in cui sappiamo la dimensione della board

Altro metodo: lasciare getAdjacentCoordinates() senza imporre il vincolo che sia < 19, anche perchè a livello generale nelle due dimensioni, un punto posizionato a sinistra di (0,0) è effettivamente (0,-1).
A quel punto non accettare coordinate negative o minori della board size se richiamato in altre classi

**Comment by mikedepetris** [comment]
la dimensione della board serve, però noi vogliamo fare board.getCell(coordinates).getAdiacentCells() ed avere la lista di tutte le celle adiacenti con le coordinate e lo stato (bianco/nero/vuoto) ?
oppure vogliamo fare un board.isAdiacentCell(coordinates1, coordinates2) ?

**Comment by martat97** [comment]
in teoria, data una cella in cui l'utente vuole inserire una pedina nera/bianca che sia, ci serve sapere se è presente almeno una cella non vuota delle 8 intorno ad essa. così viene richiamato getAdjacentCoordinates() rispetto alla coordinata corrispondente alla cella in cui sto cercando di inserire.
board.getCell(coordinates).getAdiacentCells() -> questa potrebbe andare

**Comment by mikedepetris** [comment]
sì aggiungerei che farei in modo che cell.getAdiacentCells() usi cell.getCoordinates().getAdjacentCoordinates() se vogliamo mettere un getAdjacentCoordinates() dentro all'oggetto Coordinates, altrimenti uno statico getAdjacentCoordinates(coordinates) dove appunto devi avere la board, oppure passargliela,

**Comment by biagiolicari** [comment]
Mia opinione:
Secondo me ha senso fare un metodo statico booleano all’interno della classe coordinates che ti dice se, passata un oggetto coordinate è adiacente all’oggetto this Coordinate

Nella classe board poi le funzioni per avere N celle adiacenti rispetto ad una coordinata di input
