### ISSUE TITLE
Implementazione classe Player

### ISSUE THREAD

**Issue by biagiolicari** [mikedepetris/Gomoku-SDM#5]
Classe Person:

- Username
- Colore assegnato all'inizio della partita
- Lista dei movimenti che vengono compiuti durante il game

**Comment by biagiolicari** [comment]
Implementate.
Eventuali problematiche da gestire:

1. Cosa succede se l'username non viene inserito ? Generazione random di caratteri ?
2. E' necessario impostare un num max alle pietre che ogni player ha a disposizione ?

**Comment by mikedepetris** [comment]
1. per me la cosa semplice è obbligare ad inserire un nome non vuoto
2. nelle regole non lo ho trovato, secondo me no, si va fino a riempire tutta la board

**Comment by martat97** [comment]
1. magari se non viene inserito lo user, viene mantenuto un nome di default come Player 1 (funziona così in vari giochi)
2. il numero massimo di pietre dovrebbe essere 19x19=361/2->180 per il bianco, 181 per il nero, ma direi che non serva impostarlo
