### ISSUE TITLE
limitare a 60 le mosse possibili per ogni giocatore

### ISSUE THREAD

**Issue by martat97** [mikedepetris/Gomoku-SDM#51]
Inserimento della limitazione a 60 delle mosse nei Players

**Comment by martat97** [comment]
Ok, ho controllato il codice, il test è testLimitMovesPlayer() in Game che verifica venga rispettata la regola delle 60 mosse, si basa sulla dimensione delle movesList di ogni Player. E' gestito nel metodo makeMove che con la condizione "lastMovingPlayer.getMovesList().size() <= 60" verifichi che non si raggiunga 60, ma non mi convince del tutto. Non dovrebbe essere strettamente minore di 60? Se no ciò che succede è che il player arriva a 61. Ancora non chiudo questa issue perchè devo un attimo ricontrollare

**Comment by mikedepetris** [comment]
ok la ho messa in progress, ricordati di fare il giro: new brach, creazione test, modifiche, commit, push, create PR, review, merge su master

**Comment by martat97** [comment]
ok ho risolto questo problema, chiudo la issue
