### ISSUE TITLE
MakeMove, a Game o Player?

### ISSUE THREAD

**Issue by martat97** [mikedepetris/Gomoku-SDM#65]
Al momento il metodo MakeMove viene invocato da:
Game.MakeMove(Player, Coordinata). Forse è più intuitivo Player.MakeMove(Coordinata)?
Anche perchè, al momento la classe Game ha più responsabilità: controllare se giocatore ha vinto, controllare i colori dei giocatori, far fare una mossa al giocatore, e se una mossa è valida. Dovremmo decidere di preciso cosa fa la classe Game. Oltretutto la variabile "private Coordinates lastMoveCoordinates", non dovrebbe essere necessario farla come variabile di istanza, credo anche lastMovingPlayer. Appena approviamo la pull request di Biagio, cerco di sistemare la situazione delle 2 variabili di istanza

**Comment by mikedepetris** [comment]
Come dige Biagio è corretto pensare alla classe Game come contenitore principale, piuttosto sarebbe da capire se ci sono comportamenti ed azioni che possono essere raggruppati logicamente e quindi inserirli in una classe contenuta in Game.

**Comment by mikedepetris** [comment]
Visto che il prof risponde subito sarei dell'idea di fargli questa domanda sulla classe Game ed eventuali "sottoclassi"

**Comment by biagiolicari** [comment]
Ritorno a questa discussione: se inseriamo la possibilità di giocare contro la Cpu, pensandoci bene, non sarebbe più corretto inserire la makemove dentro la classe player ? In modo che una eventuale estensione human player gestisce il movimento umano mentre una estensione cpu player va a gestire il movimento tramite un qualche algoritmo

Alleggerendo la responsabilità fra player e cpu dentro la classe game

**Comment by mikedepetris** [comment]
sì giusto quindi player.makemove che però deve scatenare i controlli di mossa valida che dipendono dallo stato di Game

**Comment by mikedepetris** [comment]
@martat97 per cortesia pone la domanda ai prof
