### ISSUE TITLE
Requisiti opzionali: scelta dimensione board

### ISSUE THREAD

**Issue by mikedepetris** [mikedepetris/Gomoku-SDM#79]
Scelta tra diverse modalità con regole del gioco diverse

**Comment by mikedepetris** [comment]
@biagiolicari Biagio Licari: 
[12:36, 19/01/2023]
È già predisposto per il cambio dimensione
Serve solo il pezzo di codice che prende in input la dimensione
E ti crea la map di quella dimensione con le coordinate

**Comment by martat97** [comment]
Sì esatto, era stata generalizzata la dimensione a posta. Quello che ho trovato su versioni alternative possibili:
- Per la dimensione normalmente la scelta è fra 19x19 (che è la vecchia standard che abbiamo messo) e 15x15 è più recente.
- La possibilità di togliere l'obbligo al primo giocatore di posizionare per forza al centro la prima pedina. Infatti in alcune versioni si può posizionare liberamente.
- La regola denominata three-and-three sembrava interessante, andrebbe inserita una funzione che controlla che non venga violata (da vedere che non sia troppo dispendioso di tempo)
- Impostare un tempo limite al giocatore, se scade il suo tempo perde (come capita ad esempio nelle partite dei campioni di scacchi che hanno un limite di tempo totale)

Comunque tutto è ricavabile da qui:
https://en.wikipedia.org/wiki/Gomoku

**Comment by mikedepetris** [comment]
Grazie Marta, aggiorno le issue separate in backlog
