### ISSUE TITLE
Requisiti opzionali: Interfaccia Grafica

### ISSUE THREAD

**Issue by mikedepetris** [mikedepetris/Gomoku-SDM#80]
Implementazione della GUI tramite Swing

**Comment by martat97** [comment]
Ho inserito una classe per la GUI, ma ancora devo sistemare delle cose (perchè non avevo visto che erano state fatte delle modifiche in questi ultimi giorni sul setup della dimensione Board).
Comunque, devo mettere in Settings, intanto, la scelta dimensione tra 15 e 19, e la possiblità di uscire. Poi funziona (almeno).
Sarebbe preferibile impostare il layout corretto come avevano detto i prof

**Comment by mikedepetris** [comment]
Come suggerivo in questa fase conviene ricordarsi di fare spesso merge da master al branch e chiudere rapidamente con la PR
Intanto ho passato questa issue "in progress" nella board.
