### ISSUE TITLE
Requisiti: 5. Get ready for the exam.

### ISSUE THREAD

**Issue by mikedepetris** [mikedepetris/Gomoku-SDM#86]
- Contact us to schedule the exam.
- Send us the link of the project repository (at least 2 days before the exam).

**Comment by mikedepetris** [comment]
- Marta chiede via email di poter sostenere l'esame nella seconda settimana di febbraio 6-10/02/23
- In base alla data di esame invieremo il link entro 2gg prima

**Comment by martat97** [comment]
Ho appena mandato la mail al prof, in attesa di risposta per decidere il giorno

**Comment by mikedepetris** [comment]
Grazie Marta, da parte mia sposterò le date degli altri esami di conseguenza

**Comment by martat97** [comment]
Per ora, deciso il 7 febbraio
