### ISSUE TITLE
Organizzare le classi nei package appositi

### ISSUE THREAD

**Issue by biagiolicari** [mikedepetris/Gomoku-SDM#96]
Dovremmo pensare ad una possibile organizzazione delle classi in appositi package in modo da rendere più pulito il codice

**Comment by mikedepetris** [comment]
Scriviamo anche "Guava" e com.google.commons per trovare facilmente la issue

**Comment by elmehdi1212** [comment]
Posso aiutarti con questo problema ?

**Comment by martat97** [comment]
Lascio un commento qui, leggendo le slide dei prof, parlando del Simple Design suggeriscono di non creare troppi Packages. Nel nostro caso potrebbe essere utile separare Gui e Cli dalle classi principali
